### PR TITLE
Architectural changes

### PR DESCRIPTION
**Pull request by Shreemanarjun**
- Added architecture using [riverpod_simple_architecture](https://brickhub.dev/bricks/riverpod_simple_architecture)
- Added Error handling using Riverpod State management
- Added Thumbnail preview on a valid url
- Added validation to url to accept only youtube urls
- Added different states
- Added no internet widget for better handling no internet connection
- Added Auto_route for routing
- Added flex_color_scheme for theming
- Added FormBuilder for download form with validation included

### CODE REVIEW

**Comment by Shreemanarjun** [comment]
@championswimmer Please review and merge.

**Comment by championswimmer** [comment]
@Shreemanarjun can we split it out into smaller changes please :) 

I am expecting these to definitely go separately (make 4 separate PRs at least) 

1. add thumbnail previews 
2. moving state to riverpod
3. routes with auto-router (this I am not sure why we even need? this is a single pager app) 
4. Url and form validations

**Comment by Shreemanarjun** [comment]
Will do .@championswimmer

**Comment by Shreemanarjun** [comment]
With this new architecture, issue #12 will not be needed as we are sending the object once the form validated.

**Comment by Shreemanarjun** [comment]
But i dont think so splitting the pr will be possible because of architectural change somehow it tightly coupled with all changes made. Needed help if possible.

**Comment by championswimmer** [comment]
@Shreemanarjun that's the whole point. These changes shouldn't be tightly coupled. 

Form validation is a sanity step. Thumbnail preview is a new feature. Riverpod is an arch refactor. They are not related things.

**Comment by Shreemanarjun** [comment]
Ok Will split into these parts.

1.   Form Validations
2. Thumbnail Preview
3. architectural  change  for Riverpod.
4. Additional ytdlp customizations.


Got it and thanks @championswimmer .

**Pull request closed without merging**
